const express = require('express')
const authRouter = require('./authRouter')
const categoryRouter = require('./categoryRouter')
const collectionRouter = require('./collectionRouter')
const collectionItemRouter = require('./collectionItemsRouter')
const itemRouter = require('./itemRouter')
const itemRequestRouter = require('./itemRequestRouter')
const itemAdvertisementRouter = require('./itemAdvertisementRouter')
const refreshRouter = require('./refreshRouter')
const userRouter = require('./userRouter')
const userFavoriteRouter = require('./userFavoritesRouter')
const userProfileRouter = require('./userProfileRouter')
const userReportRouter = require('./userReportRouter')
const userReportTypeRouter = require('./userReportTypeRouter')
const exchangeRouter = require('./exchangeRouter')
const router = express.Router()

router.use('/auth', authRouter)
router.use('/categories', categoryRouter)
router.use('/collections', collectionRouter)
router.use('/collectionitems', collectionItemRouter)
router.use('/items', itemRouter)
router.use('/itemrequests', itemRequestRouter)
router.use('/itemadvertisements', itemAdvertisementRouter)
router.use('/refresh', refreshRouter)
router.use('/users', userRouter)
router.use('/userfavorites', userFavoriteRouter)
router.use('/userprofiles', userProfileRouter)
router.use('/userreports', userReportRouter)
router.use('/userreporttypes', userReportTypeRouter)
router.use('/exchange', exchangeRouter)
module.exports = router
