version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: ScarbnikDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: your_minio_access_key
      MINIO_ROOT_PASSWORD: your_minio_secret_key
    ports:
      - '9000:9000'
    command: server /data

  nodejs:
    build: .
    container_name: nodejs
    environment:
      NODE_ENV: production
      PORT: 5000
      POSTGRES_HOST: postgres
      POSTGRES_DB: your_database
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: your_minio_access_key
      MINIO_SECRET_KEY: your_minio_secret_key
    ports:
      - '5000:5000'
    depends_on:
      - postgres
      - minio
    volumes:
      - .:/usr/src/app
